CREATE TABLE IF NOT EXISTS vaga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000) NOT NULL,
    area_conhecimento VARCHAR(255) NOT NULL,
    localizacao VARCHAR(255) NOT NULL,
    tipo_vaga INTEGER,
    periodo_turno VARCHAR(255),
    data_publicacao DATE NOT NULL,
    prazo_candidatura DATE,
    beneficios VARCHAR(255),
    salario VARCHAR(255),
    requisitos VARCHAR(255),
    empresa_id BIGINT NOT NULL,
    status INTEGER,
    CONSTRAINT pk_vaga PRIMARY KEY (id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_vaga_empresa'
    ) THEN
        ALTER TABLE vaga
            ADD CONSTRAINT fk_vaga_empresa
            FOREIGN KEY (empresa_id) REFERENCES users (id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'vaga_localizacao_check'
    ) THEN
        ALTER TABLE vaga
            ADD CONSTRAINT vaga_localizacao_check
            CHECK (localizacao IN ('PRESENCIAL', 'REMOTO', 'HIBRIDO'));
    END IF;
END $$;
