CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'users_role_check'
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT users_role_check
            CHECK (role IN ('COMPANY', 'CANDIDATE'));
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('public.vaga') IS NOT NULL AND to_regclass('public.vagas') IS NULL THEN
        ALTER TABLE vaga RENAME TO vagas;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS vagas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000) NOT NULL,
    area_conhecimento VARCHAR(255) NOT NULL,
    localizacao VARCHAR(255) NOT NULL,
    tipo_vaga VARCHAR(50),
    periodo_turno VARCHAR(255),
    data_publicacao DATE NOT NULL,
    prazo_candidatura DATE,
    beneficios VARCHAR(255),
    salario VARCHAR(255),
    requisitos VARCHAR(255),
    empresa_id BIGINT NOT NULL,
    status VARCHAR(50),
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_vagas PRIMARY KEY (id)
);

ALTER TABLE vagas
    ADD COLUMN IF NOT EXISTS ativa BOOLEAN NOT NULL DEFAULT TRUE;
