export enum StatusDaCandidatura {
  SUBMETIDA = 'SUBMETIDA',
  EM_ANÁLISE = 'EM_ANÁLISE',
  ENTREVISTA = 'ENTREVISTA',
  PROXIMA_ETAPA = 'PROXIMA_ETAPA',
  APROVADA = 'APROVADA',
  REPROVADA = 'REPROVADA',
  CANCELADA = 'CANCELADA',
}
